import fs from 'node:fs/promises';import assert from 'node:assert/strict';
import {loadDictionaries} from '../dist/dictionary-loader.mjs';import {makeEngine} from '../dist/engine.mjs';import {prepareImport} from '../dist/import-graph.mjs';
const read=p=>fs.readFile(new URL('../dist/'+p,import.meta.url),'utf8');const loaded=await loadDictionaries(read),e=makeEngine(loaded.catalogue,loaded.xml);
const base={...JSON.parse(await fs.readFile(new URL('./scenarios.json',import.meta.url)))[0].inputs,'/return/taxYear':'2025','/return/currency':'CAD','/residence/status':'residentFullYear','/residence/provinceAtYearEnd':'NS','/person/birthDate':'1990-01-01'};
for(const f of loaded.catalogue.facts.filter(f=>!f.formula&&!f.path.includes('/*/')&&['nsSetup','nsCredits','nsReduction','nsAdjustments','credits','federalAdjustments','refundableCredits','rrspRoom','rrspSchedule','donations','scheduleSetup'].includes(f.module))){if(f.path==='/credits/basicPersonal')continue;base[f.path]=f.type==='Boolean'?false:f.type==='Collection'?[]:f.type==='String'?(f.values?.[0]??''):'0';}
Object.assign(base,{'/ns/ordinaryReturnConfirmed':true,'/ns/creditsReviewed':true,'/federalTax/ordinaryReturnConfirmed':true,'/federalTax/returnReviewed':true,'/federalTax/creditInputBasis':'claimAmounts','/specialTaxes/splitIncome':'0','/specialTaxes/minimumTaxCarryover':'0','/specialTaxes/oasRecovery':'0','/payments/taxWithheld':'0','/payments/instalments':'0','/registeredPlans/rrspDeductionLimit':'20000','/schedule9/reviewed':true,'/schedule7/reviewed':true});
const id='44444444-4444-4444-8444-444444444444';const income=n=>({'/properties':[id],[`/properties/#${id}/net`]:String(n)});
const gift=(amount,year=2025,category='charity',claim=amount)=>({'/donationGifts':[id],[`/donationGifts/#${id}/giftYear`]:String(year),[`/donationGifts/#${id}/category`]:category,[`/donationGifts/#${id}/available`]:String(amount),[`/donationGifts/#${id}/claim`]:String(claim),'/schedules/useDonations':true});
function r(p,changes={},missing=[]){const inputs={...base,...changes};for(const k of missing)delete inputs[k];return e.result(e.build(inputs),p);}
function check(p,v,changes={},missing=[]){const a=r(p,changes,missing);assert.equal(a.error,undefined,p+' '+a.error);if(v===null)assert.equal(a.complete,false,p);else{assert.equal(a.complete,true,p+' '+JSON.stringify(a));assert.equal(a.value,String(v),p);}}
check('/schedule9/federalCredit','261.00',{...income(50200),...gift(1000)});
check('/schedule9/novaScotiaCredit','185.58',{...income(50200),...gift(1000)});
check('/ns/donationCredit','185.58',{...income(50200),...gift(1000),'/ns/eligibleDonations':'9999'});
check('/federalTax/netFederalTax','4679.29',{...income(50200),...gift(1000),'/credits/donations':'9999'});
check('/federalTax/totalPayable','9087.08',{...income(50200),...gift(1000)});
check('/schedule9/federalCredit','260.00',{...income(50200),...gift(1000),'/return/taxYear':'2026'});
check('/schedule9/federalCredit','3263.00',{...income(300000),...gift(10000)});
check('/schedule9/federalCredit','2894.44',{...income(254000),...gift(10000)});
check('/schedule9/federalCredit','2871.00',{...income(300000),...gift(10000,2015,'ecological')});
check('/schedule9/claimedGifts',null,{...income(300000),...gift(10000,2015,'ecological'),'/return/taxYear':'2026'});
check('/schedule9/ordinaryLimit','750.00',income(1000));
check('/schedule9/claimedGifts',null,{...income(1000),...gift(751)});
check('/schedule9/ordinaryLimit','850.00',{...income(1000),'/schedule9/giftTaxableCapitalGains':'400'});
check('/schedule9/claimedGifts','5000.00',{...income(1000),...gift(5000,2025,'cultural')});
check('/schedule9/claimedGifts',null,{...income(10000),...gift(100,2025,'charity',101)});
check('/schedule9/claimedGifts',null,{...income(10000),...gift(100,2026,'charity',0)});
check('/schedule9/expiredUnclaimed','150.00',{...income(10000),...gift(250,2020,'charity',100)});
check('/schedule9/carryforward','0.00',{...income(10000),...gift(250,2020,'charity',100)});
check('/schedule9/carryforward','150.00',{...income(10000),...gift(250,2025,'charity',100)});
check('/schedule9/federalCredit',null,{...income(10000),...gift(100),'/schedule9/reviewed':false});
const room={'/rrspRoom/priorDeductionLimit':'20000','/rrspRoom/priorOrdinaryDeduction':'5000','/rrspRoom/priorEmployerPrpp':'1000','/rrspRoom/employmentIncome':'100000','/rrspRoom/pensionAdjustment':'6000','/rrspRoom/pensionAdjustmentReversal':'2000','/rrspRoom/exemptPspa':'1000','/rrspRoom/certifiedPspa':'500','/rrspRoom/qualifyingWithdrawals':'200'};
check('/rrspRoom/openingRoom','14000.00',room);
check('/rrspRoom/earnedIncome','100000.00',room);
check('/rrspRoom/newRoom','12000.00',room);
check('/rrspRoom/netPspa','1300.00',room);
check('/rrspRoom/estimatedDeductionLimit','26700.00',room);
check('/rrspRoom/newRoom','32490.00',{'/rrspRoom/employmentIncome':'1000000'});
check('/rrspRoom/newRoom','33810.00',{'/rrspRoom/employmentIncome':'1000000','/return/taxYear':'2026'});
check('/rrspRoom/earnedIncome','-1000.00',{'/rrspRoom/businessLosses':'1000'});
check('/rrspRoom/newRoom','0.00',{'/rrspRoom/businessLosses':'1000'});
check('/rrspRoom/earnedIncome','1100.00',{'/rrspRoom/employmentIncome':'1000','/rrspRoom/royalties':'100','/rrspRoom/unionDues':'200','/rrspRoom/rentalIncome':'500','/rrspRoom/deductibleSupport':'200'});
check('/rrspRoom/estimatedDeductionLimit','0.00',{'/rrspRoom/openingRoomProvided':true,'/rrspRoom/openingUnusedRoom':'-1000'});
check('/rrspRoom/unflooredLimit','-1000.00',{'/rrspRoom/openingRoomProvided':true,'/rrspRoom/openingUnusedRoom':'-1000'});
check('/rrspRoom/netPspa','-500.00',{'/rrspRoom/qualifyingWithdrawals':'500'});
check('/rrspRoom/estimatedDeductionLimit','500.00',{'/rrspRoom/qualifyingWithdrawals':'500'});
const schedule={'/schedules/useRrsp':true,'/schedule7/openingUnusedContributions':'5000','/schedule7/ownMainPeriod':'10000','/schedule7/spousalMainPeriod':'2000','/schedule7/ownFollowing60Days':'3000','/schedule7/spousalFollowing60Days':'1000','/schedule7/hbpRepayment':'2000','/schedule7/llpRepayment':'1000','/schedule7/hbpRequired':'2500','/schedule7/llpRequired':'1000','/schedule7/employerPrpp':'1000','/schedule7/eligibleTransfers':'4000','/schedule7/ordinaryDeductionChosen':'10000'};
check('/schedule7/newContributions','16000.00',schedule);
check('/schedule7/availableToDeduct','18000.00',schedule);
check('/schedule7/maxOrdinaryDeduction','14000.00',schedule);
check('/schedule7/deduction','14000.00',schedule);
check('/schedule7/unusedContributionsCarryforward','4000.00',schedule);
check('/schedule7/shortfallIncome','500.00',schedule);
check('/income/netIncome','86500.00',{...income(100000),...schedule});
check('/rrspRoom/additionalContributionSpace','14000.00',schedule);
check('/rrspRoom/targetYearCapacityAfterReportedContributions','5000.00',schedule);
check('/rrspRoom/unusedDeductionRoomCarryforward','15700.00',{...room,...schedule});
check('/schedule7/deductionLimit','26700.00',{...room,...schedule,'/schedule7/limitSource':'t4040Estimate'});
check('/rrspRoom/contributionSpaceBeforeNewDeposits','-1000.00',{'/schedule7/openingUnusedContributions':'21000'});
check('/rrspRoom/additionalContributionSpace','0.00',{'/schedule7/openingUnusedContributions':'21000'});
check('/schedule7/deduction',null,{...schedule,'/schedule7/ordinaryDeductionChosen':'14000.01'});
check('/income/netIncome',null,{...schedule,...income(100000),'/schedule7/reviewed':false});
check('/schedule7/deduction',null,{'/schedules/useRrsp':true,'/schedule7/spousalMainPeriod':'5000','/schedule7/hbpRepayment':'1000'});
check('/schedule7/deduction',null,{...schedule,'/schedule7/eligibleTransfers':'14000'});
check('/schedule7/deduction',null,schedule,['/registeredPlans/rrspDeductionLimit']);
check('/schedule7/deduction',null,{...schedule,'/return/taxYear':'2027'});
check('/schedule7/shortfallIncome','500.00',{...schedule,'/schedule7/hbpWithdrawals':'60000','/schedule7/llpWithdrawals':'10000'});
check('/income/netIncome','100000.00',{...income(100000),...schedule,'/schedules/useRrsp':false});
const both={...base,...income(100000),...schedule,...gift(1000)};const g=e.build(both),restored=prepareImport(g.toJSON(),e);assert.equal(restored.inputs['/schedule7/reviewed'],undefined);assert.equal(restored.inputs['/schedule9/reviewed'],undefined);assert.equal(e.result(restored.graph,'/income/netIncome').complete,false);
assert.ok(e.constraints({...base,...gift(100,2025,'charity',101)}).some(x=>x.startsWith('Schedule 9')));
assert.ok(e.constraints({...base,...schedule,'/schedule7/ordinaryDeductionChosen':'15000'}).some(x=>x.startsWith('Schedule 7')));
const manifest=JSON.parse(await read('./dictionary-modules.json'));const altered=structuredClone(manifest);altered.modules.at(-1).replaces=['/payments/taxWithheld'];await assert.rejects(()=>loadDictionaries(p=>p==='./dictionary-modules.json'?Promise.resolve(JSON.stringify(altered)):read(p)),/Replacement must target an existing derived fact/);
check('/schedule9/ordinaryLimit','64875.00',{...income(100000),...schedule});
check('/schedule9/claimedGifts','63000.00',{...income(100000),...schedule,...gift(63000)});
check('/schedule9/claimedGifts',null,{...income(100000),...schedule,...gift(63000),'/schedule7/ordinaryDeductionChosen':'14000'});
check('/federalTax/netFederalTax',null,{...income(10000),...gift(100),'/schedule9/reviewed':false});
const originalScenarios=JSON.parse(await fs.readFile(new URL('./scenarios.json',import.meta.url)));
for(const scenario of originalScenarios){const i={...(scenario.inherit_zero?originalScenarios[0].inputs:{}),...scenario.inputs};for(const key of scenario.remove??[])delete i[key];const graph=e.build(i);for(const [path,value]of Object.entries(scenario.expected)){const result=e.result(graph,path);if(value==='MISSING')assert.equal(result.complete,false,path);else{assert.equal(result.complete,true,path);assert.equal(result.value,typeof value==='boolean'?String(value):Number(value).toFixed(2),path);}}}
check('/schedule7/deduction',null,{'/schedules/useRrsp':true,'/schedule7/ownMainPeriod':'10000','/schedule7/spousalMainPeriod':'10000','/schedule7/hbpRepayment':'10000','/schedule7/eligibleTransfers':'10000'});
check('/schedule9/ordinaryLimit','875.00',{...income(1000),'/donatedDepreciable':[id],[`/donatedDepreciable/#${id}/recapture`]:'600',[`/donatedDepreciable/#${id}/eligiblePropertyTotal`]:'500'});
console.log('PASS: Schedule 9 dual-jurisdiction credits, 33% tier, old ecological gifts, income limits, expiry and carryforward; T4040 signed room, earned income, caps/PA/PAR/PSPA; Schedule 7 transfers/designations/deductions/carryforwards and automatic income posting; review/validation gates, import and protected overlays.');
// Next-year Chart 3 reads source details rather than duplicate worksheet inputs.
const detailBase={...base,'/employments':[],'/businesses':[],'/properties':[],'/otherIncome':[],'/subdivisionEDeductions':[]};
for(const f of loaded.catalogue.facts.filter(f=>f.module==='nextYearRrsp'&&!f.formula))detailBase[f.path]=f.type==='Boolean'?false:'0';
function job(amount){const a={'/employments':[id],[`/employments/#${id}/remuneration`]:String(amount)};for(const name of ['benefits','optionBenefits','deductions','royalties','researchGrants','supplementaryUnemployment','wageProtection','unionDues','employmentExpenses','employmentIncomeAdjustment'])a[`/employments/#${id}/${name}`]='0';return a;}
const nextCase={...detailBase,...job(100000),'/nextYearRrsp/openingUnusedRoom':'14000','/nextYearRrsp/pensionAdjustment':'6000','/nextYearRrsp/pensionAdjustmentReversal':'2000','/nextYearRrsp/exemptPspa':'1000','/nextYearRrsp/certifiedPspa':'500','/nextYearRrsp/qualifyingWithdrawals':'200'};
check('/nextYearRrsp/targetYear','2026',nextCase);
check('/nextYearRrsp/estimatedDeductionLimit','26700.00',nextCase);
check('/nextYearRrsp/newRoom','33810.00',{...detailBase,...job(1000000)});
check('/nextYearRrsp/newRoom','35390.00',{...detailBase,...job(1000000),'/return/taxYear':'2026'});
check('/nextYearRrsp/estimatedDeductionLimit','0.00',{...detailBase,'/nextYearRrsp/openingUnusedRoom':'-1000'});
check('/nextYearRrsp/estimatedDeductionLimit',null,nextCase,['/nextYearRrsp/pensionAdjustment']);
check('/nextYearRrsp/estimatedDeductionLimit',null,{...nextCase,'/return/taxYear':'2027'});
check('/nextYearRrsp/openingRoom','26700.00',{...detailBase,...room},['/nextYearRrsp/useCalculatedCarryforward']);
check('/nextYearRrsp/earnedIncome','97000.00',{...detailBase,...job(100000),[`/employments/#${id}/unionDues`]:'1000',[`/employments/#${id}/employmentExpenses`]:'2000'});
const biz={...detailBase,'/businesses':[id],[`/businesses/#${id}/net`]:'10000',[`/businesses/#${id}/activeForRrsp`]:true,[`/businesses/#${id}/athleteTrustDistributions`]:'1000',[`/businesses/#${id}/eligibleCapitalGains`]:'500'};
check('/nextYearRrsp/earnedIncome','8500.00',biz);
check('/nextYearRrsp/earnedIncome','0.00',{...biz,[`/businesses/#${id}/activeForRrsp`]:false});
check('/nextYearRrsp/earnedIncome','-1000.00',{...biz,[`/businesses/#${id}/net`]:'-1000',[`/businesses/#${id}/athleteTrustDistributions`]:'0',[`/businesses/#${id}/eligibleCapitalGains`]:'0'});
check('/nextYearRrsp/earnedIncome',null,biz,[`/businesses/#${id}/activeForRrsp`]);
const rent={...detailBase,'/properties':[id],[`/properties/#${id}/net`]:'2000',[`/properties/#${id}/sourceType`]:'realPropertyRental'};
check('/nextYearRrsp/earnedIncome','2000.00',rent);
check('/nextYearRrsp/earnedIncome','0.00',{...rent,[`/properties/#${id}/sourceType`]:'otherProperty'});
check('/nextYearRrsp/earnedIncome','-2000.00',{...rent,[`/properties/#${id}/net`]:'-2000'});
check('/nextYearRrsp/earnedIncome',null,rent,[`/properties/#${id}/sourceType`]);
check('/nextYearRrsp/athleteTrustIncome','700.00',{...detailBase,'/schedule7/athleteTrustContributions':'700'});
check('/nextYearRrsp/supportIncome','1200.00',{...detailBase,'/otherIncome':[id],[`/otherIncome/#${id}/category`]:'support',[`/otherIncome/#${id}/amount`]:'1200'});
check('/nextYearRrsp/deductibleSupport','900.00',{...detailBase,'/subdivisionEDeductions':[id],[`/subdivisionEDeductions/#${id}/category`]:'support',[`/subdivisionEDeductions/#${id}/amount`]:'900'});
const imported=prepareImport(JSON.stringify({format:'canadian-tax-graph',inputs:{...detailBase,...job(50000),'/nextYearRrsp/employmentIncome':'999999'}}),e);
assert.equal(imported.inputs['/nextYearRrsp/employmentIncome'],undefined);
assert.equal(e.result(imported.graph,'/nextYearRrsp/employmentIncome').value,'50000.00');
assert.throws(()=>prepareImport(JSON.stringify({format:'canadian-tax-graph',inputs:{'/subdivisionEDeductions':[id],[`/subdivisionEDeductions/#${id}/category`]:'rrsp'}}),e),/Move that record to Schedule 7/);
assert.throws(()=>e.validate(`/subdivisionEDeductions/#${id}/category`,'rrsp'),/available options/);
console.log('PASS: Source-linked next-year RRSP calculations, classifications, missing-input handling, annual ceilings and legacy import protections.');
